### ISSUE TITLE
"brew pip" command does not work

### ISSUE THREAD

**Issue by brunobord** [edavis/brew-pip#2]
If I'm trying to use "brew pip" the way it is stated in your readme file, it simply does not work and returns the following message:

```
$ brew pip stuff
Error: Unknown command: pip
```

It looks like using the brew-pip script works like a charm, for example, I can install ipython this way:

```
$ brew-pip ipython
```

Oh, and by the way, unfortunately, there is no such thing as "brew rm".

Don't you think the Readme file needs to be updated to reflect the actual commands?

**Comment by edavis** [comment]
Make sure brew-pip has the executable bit set (`chmod +x`) and is in your $PATH.

`brew rm` is an alias to `brew remove`, but one thing that did change recently is all packages installed with brew-pip have 'pip-' prepended to them. So it's `brew rm pip-django` now.

The README and the code has diverged, though, for sure. I'll try polishing it up in the next couple days.

Thanks.

**Comment by brunobord** [comment]
ha... same comment than the other issue: maybe that was because my ~/bin directory wasn't in the $PATH. Will have to test it again when I'll be on my home machine... (to be continued)

**Comment by brunobord** [comment]
my fault, it does work fine. sorry for the noise.
