### ISSUE TITLE
How to define pypi dependencies in brew?

### ISSUE THREAD

**Issue by brejoc** [edavis/brew-pip#4]
Sorry, if I'm in the wrong repo!

Would it be possible to tell homebrew to treat e.g. invoke (a Python package from the cheese shop) as a dependency that can only be statisfied through brew-pip? Normally dependencies would be defined with `depends_on`, but I'm not sure how this should work.

**Comment by edavis** [comment]
Hi there — this project is no longer being maintained (or even used by me). https://github.com/Homebrew/homebrew/pull/24557 has more info.

If you still need an answer to this question, I'd check in with Homebrew proper. Thanks!
